### ISSUE TITLE
Одновременное распознавание голоса и запись звука

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#115]
В коде проекта есть Activity, где происходит подсчет доли пауз в речи докладчика.
Также известно, что одновременно с распознаванием это не работает.

Задача:
- пофиксить одновременную работу,
- выводить в качестве одного из статистических показателей долю пауз.

**Comment by Evgenijjjj** [comment]
#364 #365

**Comment by zmm** [comment]
:+1:
