### ISSUE TITLE
Добавить поддержку Google Analytics

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#208]
- Изучите, как добавить поддержку в приложение минимальными усилиями 
- изучите, как сделать так, чтобы ключ доступа к GA можно было не светить в исходниках и подключать только для релиз-сборок

**Comment by rosshkaa** [comment]
https://github.com/OSLL/android_public_speech_trainer/wiki/Google-analytics

**Comment by zmm** [comment]
Разбейте пожалуйста работу по подключению GA на набор задач (которые нужно создать в трекере), каждая не более двух часов рабочего времени.

**Comment by rosshkaa** [comment]
* https://github.com/OSLL/android_public_speech_trainer/issues/292
* https://github.com/OSLL/android_public_speech_trainer/issues/293
* https://github.com/OSLL/android_public_speech_trainer/issues/284
* https://github.com/OSLL/android_public_speech_trainer/issues/285
