### ISSUE TITLE
Проблемы с производительностью первой activity

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#227]
-научиться складывать первый слайд презентации в виде blob поля в БД и загружать его

**Comment by zmm** [comment]
Конфликты

**Comment by zmm** [comment]
Падают тесты 

![image](https://user-images.githubusercontent.com/717575/53582833-5abad080-3b91-11e9-989e-0bc891095030.png)

**Comment by zmm** [comment]
Теперь падают все тесты из TestDatabase.kt

**Comment by Evgenijjjj** [comment]
Такое может быть из-за различия стартовых конфигураций. Все тесты прошли при наличии презентаций в БД и при переустановке приложения (в этом случае нужно разрешить permissions, затем запускать тесты)

<img src="https://i.ibb.co/SN4HmPy/2019-03-07-14-26-33.png" alt="2019-03-07-14-26-33" border="0">
