### ISSUE TITLE
Разметка карточки презентации

### ISSUE THREAD

**Issue by rosshkaa** [OSLL/android_public_speech_trainer#268]
При длине названия презентации более 15-ти символов, текст названия пересекается с иконками в карточке.
Необходимо увеличить вертикальное расстояние между названием и иконками в карточке презентации таким образом, чтобы:
- название не пересекалось с иконками
- иконки не пересекались с границами карточки
Необходимо протестировать модификацию на устройствах различных размеров и форматов

**Comment by KateYurut** [comment]
Уже было исправлено.
