### ISSUE TITLE
Добавить информацию о том как приложение использует android id в privacy policy

### ISSUE THREAD

**Issue by Evgenijjjj** [OSLL/android_public_speech_trainer#309]

**Comment by rosshkaa** [comment]
Уточните пожалуйста, какой PR относится к этой задаче

**Comment by Evgenijjjj** [comment]
> Уточните пожалуйста, какой PR относится к этой задаче

https://github.com/OSLL/android_public_speech_trainer/wiki/%D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B4%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8
