### ISSUE TITLE
Сохранять оценку за тренировку в firebase в детализированном виде (x, y, z)

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#322]

**Comment by zmm** [comment]
Добавьте детализованное сохранение оценки для каждой тренировки. 
Также прошу сохранять каждый критерий в отдельном поле.

**Comment by rosshkaa** [comment]
Уточните пожалуйста, какой ПР соответствует данной задаче

**Comment by KateYurut** [comment]
https://github.com/OSLL/android_public_speech_trainer/pull/346
