### ISSUE TITLE
Критерий полноты законченности тренировки

### ISSUE THREAD

**Issue by MikelDementyev** [OSLL/android_public_speech_trainer#329]
Создать Вики-страничку с вариантами, когда пользователь может рассказать малое количество слайдов, и это будет являться нормой.

**Comment by rosshkaa** [comment]
Пожалуйста, уточните вики-страницу, которая решают данную issue

**Comment by MikelDementyev** [comment]
> Пожалуйста, уточните вики-страницу, которая решают данную issue

https://github.com/OSLL/android_public_speech_trainer/wiki/Причины-допустимых-ситуаций,-когда-пользователь-рассказал-малое-количество-слайдов.
