### ISSUE TITLE
Падает при попытке начать тренировку на google pixel 2

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#342]
Детали можно узнать у Татьяны Берленко.

**Comment by Evgenijjjj** [comment]
Связался с Татьяной, воспроизвел сценарий краша ("Падает при нажатии на презентацию в списке презентаций, чтобы начать тренировку") на эмуляторе pixel 3 android 9 все работает исправно. Логи краша получить не удалось.
