### ISSUE TITLE
Отобразить долю слов-паразитов / словестного мусора на статистике тренировки

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#343]

**Comment by zmm** [comment]
Не нашел отображение доли в статистике тренировки.

**Comment by MikelDementyev** [comment]
Решение проблемы с неотображением доли слов паразитов:

https://github.com/OSLL/android_public_speech_trainer/pull/439

**Comment by MikelDementyev** [comment]
> Не нашел отображение доли в статистике тренировки.

Решение проблемы с неотображением доли слов паразитов:

https://github.com/OSLL/android_public_speech_trainer/pull/439
