### ISSUE TITLE
Jenkins job с проверкой собираемости проекта по коммитам (по аналогии с travis)

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#344]
Запустите Docker образы с эмулятором и sdk.
Используйте следующие команды в качестве проверок

``` 
mv "app/google-services-debug.json" "app/google-services.json"
./gradlew assembleDebug
./gradlew assembleAndroidTest
./gradlew lintDebug
```

**Comment by rosshkaa** [comment]
Добавить логику проверки конфликтов

**Comment by rosshkaa** [comment]
Добавить всех участников в получатели писем

**Comment by rosshkaa** [comment]
Прикреплять лог сборки к письму

**Comment by rosshkaa** [comment]
Решение бага существует [ссылка](https://stackoverflow.com/questions/52526219/docker-mkdir-read-only-file-system), однако оно требует переустановки docker на сервере Jenkins.
