### ISSUE TITLE
Кнопка "Экспорт статистики" должна отключатся в настройках

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#353]
1. Добавьте в секцию Debug флаг "Экспорт статистики", который выключен по умолчанию.
Если данный флаг включен (true), то на "Статистике тренировки" не должна отображаться кнопка "Экспорт статистики.

2. Добавьте тест для проверки работы данной функциональности.

**Comment by rosshkaa** [comment]
Комментарии в https://github.com/OSLL/android_public_speech_trainer/pull/366

**Comment by Villain123** [comment]
ссылка на пулреквест https://github.com/OSLL/android_public_speech_trainer/pull/403
исправлены конфликты, нужно замержить
