### ISSUE TITLE
Перенос логики AudioAnalyzer в отдельный модуль

### ISSUE THREAD

**Issue by Evgenijjjj** [OSLL/android_public_speech_trainer#364]
PR https://github.com/OSLL/android_public_speech_trainer/pull/411

**Comment by rosshkaa** [comment]
PR: https://github.com/OSLL/android_public_speech_trainer/pull/372
Revert: https://github.com/OSLL/android_public_speech_trainer/pull/388
После интеграции перестал работать сбор статистики слов

**Comment by Evgenijjjj** [comment]
> PR: #372
> Revert: #388
> После интеграции перестал работать сбор статистики слов

Дело в том, что в наше приложение собирает огромное количество статистики и "сбор статистики слов" звучит очень абстрактно, можно по-подробней описать проблему, пожалуйста.
