### ISSUE TITLE
Интеграция модуля анализа голоса в TrainingActivity

### ISSUE THREAD

**Issue by Evgenijjjj** [OSLL/android_public_speech_trainer#365]
PR https://github.com/OSLL/android_public_speech_trainer/pull/411

**Comment by zmm** [comment]
В декомпозированной задачи не появилось отображение доли пауз в статистике тренировки.

https://github.com/OSLL/android_public_speech_trainer/issues/115

**Comment by Evgenijjjj** [comment]
Декомпозировал: #380, #379, #381
