### ISSUE TITLE
Интерфейс рекомендации 

### ISSUE THREAD

**Issue by rosshkaa** [OSLL/android_public_speech_trainer#374]
Необходимо после отображения детализации оценки в статистике тренировки добавить кнопку с подписью "Как улучшить оценку?". 
По нажатию открывается RecomendationActivity, имеющая следующий вид:
* TextView (id "recomendationLabel", text "Рекомендации к выступлению") 
* TextView (id "slidesTimeLabel", text "Время слайдов") 
* TextView (id "slidesTimeRecomendation", text "Рекомендации по времени слайдов - заглушка") 
* TextView (id "slidesFrequency", text "Время слайдов") 
* TextView (id "slidesFrequencyRecomendation", text "Рекомендации по частоте слов - заглушка") 
* TextView (id "scumWordsLabel", text "Слова паразиты") 
* TextView (id "scumWordsRecomendation", text "Рекомендации по словам-паразитам - заглушка") 
* Button (id "backToStatistics", text "Назад к статистике"). По нажатию осуществляется переход к окну, из которого была вызвана RecomendationActivity (статистика последней тренировки).
* Button (id "toHomeScreen"), text "На главную"). По нажатию осуществляется переход к StartPageActivity.

Также необходимо добавить Espresso-тест:
* отображение всех элементов управления;
* отображение корректных текстов в текстовых полях;
* кнопки открывают соответствующие Activity по нажатию.

**Design mockup TBD**

**Comment by rosshkaa** [comment]
PR не проходит проверки https://github.com/OSLL/android_public_speech_trainer/pull/390/checks?check_run_id=135440553

**Comment by Villain123** [comment]
ссылка на пулреквест https://github.com/OSLL/android_public_speech_trainer/pull/405/
