### ISSUE TITLE
Эталон частоты слов и времени на слайд

### ISSUE THREAD

**Issue by rosshkaa** [OSLL/android_public_speech_trainer#376]
Необходимо собрать выборку (достаточно 5-ти) качественных презентаций (например, Кирилла Владимировича) и оценить:
* среднюю частоту слов всего выступления;
* среднюю частоту слов на 1 слайд;
* предельное отклонение от средней частоты слов на 1 слайд;

* среднее время на 1  слайд;
* предельное отклонение от среднего времени на 1 слайд.

**Comment by rosshkaa** [comment]
https://github.com/OSLL/android_public_speech_trainer/wiki/%D0%AD%D1%82%D0%B0%D0%BB%D0%BE%D0%BD-%D1%87%D0%B0%D1%81%D1%82%D0%BE%D1%82%D1%8B-%D1%81%D0%BB%D0%BE%D0%B2-%D0%B8-%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8-%D0%BD%D0%B0-%D1%81%D0%BB%D0%B0%D0%B9%D0%B4

**Comment by MikelDementyev** [comment]
Подкорретированное решение: 
https://github.com/OSLL/android_public_speech_trainer/wiki/Эталон-частоты-слов-и-времени-на-слайд
