### ISSUE TITLE
Рекомендации по скорости слайдов

### ISSUE THREAD

**Issue by rosshkaa** [OSLL/android_public_speech_trainer#378]
Необходимо реализовать:
* Оценку времени, затраченного на каждый слайд;
* Вычисление среднего времени, затраченного на каждый слайд;
* Сгенерировать текст рекомендации времени слайдов. Рекомендация имеет следующий вид:  

-- Если среднее время слайдов отличается от эталонного более, чем на пределельное значение отклонения (эти параметры - среди результатов задачи https://github.com/OSLL/android_public_speech_trainer/issues/376) выводить в поле "slidesTimeRecomendation" текст "Скорость демонстрации слайдов Вашей презентации существенно отличается от рекомендуемой. Попробуйте повысить/понизить _(в зависимости от направления отклонения)_ время отображения слайдов.

-- Если среднее время слайдов  в пределах нормы, необходимо определить слайды, время которых отличается от средней более, чем на пределельное значение отклонения, сгруппировать их по направлению отклонения (например, на слайдах 1,2,3 - сильно ниже среднего, на слайдах 4,5,6 - сильно выше среднего) и выводить в поле "slidesTimeRecomendation" текст "Скорость демонстрации слайдов ### существенно превышает среднее значение. Рекомендуется повысить время отображения указанных слайдов. При этом, скорость демонстрации слайдов ### существенно ниже среднего значения. Рекомендуется снизить время отображения указанных слайдов.".

В целях производительности, рекомендуется вычислять указанные значения параллельно отображению статистики тренировки (например, в корутине), а не при нажатии на кнопку "Как улучшить оценку".

Интерфейс размещения - результат https://github.com/OSLL/android_public_speech_trainer/issues/374

**Comment by Villain123** [comment]
ссылка на пулреквест https://github.com/OSLL/android_public_speech_trainer/pull/406
