### ISSUE TITLE
Рекомендации по словам-паразитам

### ISSUE THREAD

**Issue by rosshkaa** [OSLL/android_public_speech_trainer#383]
Необходимо реализовать:
* Сбор слов-паразитов, замеченных в презентации
* Сгенерировать текст рекомендации и выводить в поле "scumWordsRecomendation". Текст "В тексте презентации замечен набор слов-паразитов. Несмотря на то, что некоторые из этих слов могут служить в качестве логических связок, их чрезмерное присутствие в выступлении не рекомендуется. Список слов-паразитов: (с новой строки, по 1 слову в строке)".

В целях производительности, рекомендуется вычислять указанные значения параллельно отображению статистики тренировки (например, в корутине), а не при нажатии на кнопку "Как улучшить оценку".

Интерфейс размещения - результат https://github.com/OSLL/android_public_speech_trainer/issues/374

**Comment by zmm** [comment]
На экране рекомендаций написано "Рекомендации по словам-паразитам - заглушка", не увидел собственно вычисления и размещения рекомендации в коде.
