### ISSUE TITLE
Если молчать в течении тренировки, то оценка будет NaN

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#399]
https://pp.userapi.com/c855616/v855616352/5aea9/ca7Z-t80LB8.jpg

Необходимо:
- поправить логику так, чтобы за подобную тренировку выставлялось 0 баллов
- написать тест

**Comment by rosshkaa** [comment]
Пожалуйста, указывайте пулл-реквест в комментариях к issue (если имя PR и issue не совпадает).
В случае с https://github.com/OSLL/android_public_speech_trainer/pull/400 необходимо разрешить конфликт и разделить изменения таким образом, чтобы на каждую issue приходился только один PR и наоборот.

**Comment by zmm** [comment]
Темп речи NaN - поправьте и его пожалуйста.

**Comment by Villain123** [comment]
Замержено, нужно удалить задание
