### ISSUE TITLE
Безопасные миграции

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#402]
При обновлении схемы БД и обновлении приложение не должно крашится 

1. Необходимо реализовать надежный onUpdate
https://stackoverflow.com/questions/16890774/android-sqlite-database-and-app-update

- изучить какие таблицы / колонки добавились с прошлого релиза
- добавить alter запросы на добавление новых объектов и заполнение их безопасными значениями по отдельности, например - проверили что нет колонки А -> добавили колонку А и заполнили безопасными значениями

Как проверить: 
- устанавливаем версию из старого мастера со старой схемой БД
- накатываем текущую ветку
- проверяем что ничего не упало

2. Нужна инструкция в картинках, как пользователю почистить БД

**Comment by rosshkaa** [comment]
Пример старой миграции: https://github.com/OSLL/android_public_speech_trainer/blob/master/app/src/main/java/ru/spb/speech/database/Migrations.kt
