### ISSUE TITLE
Добавление доли пауз в качестве критерия 

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#420]
Если общая доля пауз > 50%, то уменьшаем критерий пропорционально ее величине. Соответственно 0 за этот критерий если пауз 100%. 

Если пауз

Что нужно сделать:
- оценивание,
- отображение критериев,
- запись в БД
- миграции
- тесты
- вики-страницу с описанием сути критериев
- описание критериев в приложении

Задачу нужно декомпозировать!

**Comment by rosshkaa** [comment]
Задача декомпозирована на #426 #427 #428 #429 #430
