### ISSUE TITLE
Оценивание доли пауз

### ISSUE THREAD

**Issue by rosshkaa** [OSLL/android_public_speech_trainer#426]
Необходимо добавить критерий пауз в оценку.  
Оценка по критерию пауз рассчитывается следующим образом:   
* паузы занимают менее 50% презентации - оценка 100% (1)
* паузы занимают более 50% - оценка = 100 - (% пауз - 50) * 2
Например, если доля пауз занимает 60% презентации, оценка по паузам - 0.8.
Критерий пауз считается равноценным другим критериям

**Comment by zmm** [comment]
Провожу тренировку - Доля пауз 0,0 ; Суммарная доля пауз - 12,49%

Кажется, что одна из цифр неверна.

**Comment by zmm** [comment]
Комментарий выше не актуален
