### ISSUE TITLE
Рекомендации в Статистике тренировки

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#43]
На основании оценки тренировки формировать (на Статистике тренировки) советы и рекомендации по улучшению доклада.

В декомпозиции нужно учесть:
- создание текстов сообщений
- интерфейса исполнения
- описать механизм на вики
- продумать тесты

**Comment by zmm** [comment]
Идея:
- общая оценка складывается из отдельных [критериев](https://github.com/OSLL/android_public_speech_trainer/wiki/%D0%92%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-%D0%B7%D0%B0-%D1%82%D1%80%D0%B5%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D1%83) 
- каждый критерий имеет физический смысл
- нужно заготовить простые рекомендации для крайних значений критериев:
-- X - слишком быстрый доклад и превышение регламента 
-- Y - слишком медленно и слишком быстро (предложить конкретные слайды, где говорить медленнее / быстрее)
-- Z - слайды где пользователь остается слишком долго / слишком мало ( сказать на каких слайдах нужно провести больше / меньше времени, предложить переформатировать презентацию)

**Comment by rosshkaa** [comment]
https://github.com/OSLL/android_public_speech_trainer/wiki/%D0%A0%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8
