### ISSUE TITLE
Поставить в мастере тег прошлого релиза

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#442]
Определите дату и время
Поставьте тег с соответствующей версией в мастере на нужном коммите

**Comment by rosshkaa** [comment]
Коммит последнего релиза - https://github.com/OSLL/android_public_speech_trainer/commit/5a9b590b169dbb6a5e7e8a81bb1ddcc8ddc7b24e
Версия в Play Market - 1.4 от 22-го мая.
