### ISSUE TITLE
Пример работы с Google-дисками через Android-приложение

### ISSUE THREAD

**Issue by MikelDementyev** [OSLL/android_public_speech_trainer#486]
Авторизация
Проверка доступа
Проверка объема свободного дискового пространства
Создание каталогов
Загрузка файлов

**Comment by MikelDementyev** [comment]
Пример:

https://riptutorial.com/ru/android/example/31947/интеграция-google-диска-в-android

**Comment by zmm** [comment]
Создайте необходимые примеры в playground/ нашего репозитория
