### ISSUE TITLE
Модель данных 

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#7]
Создайте таблицы:
- presentations
  - данные о презентации
  - путь к файлу
- trainings
  - id презентации
  - порядковый номер 
  - общая длительность
  - ...
- training_slide
  - id тренировки
  - номер слайда
  - распознанные слова
  - длительность
  - ....

Реализуйте классы для взаимодействия с таблицами с помощью Room

**Comment by PutkovDimi** [comment]
https://github.com/OSLL/android_public_speech_trainer/wiki/Модель-базы-данных

**Comment by zmm** [comment]
1. Не увидел классов и вообще пулл-реквеста.
2. Добавьте сохранение даты тренировки.
3. Слово Data можно убрать из названия таблиц.
4. Вы уверены что в sqlite есть поддержка массивов? Если да, то приложите ссылку на документацию, если нет, то пожалуйста используйте типовое решение по хранению массивов в реляционных БД. Это замечание относится в целом к TrainingsSlideData
5. var generalDuration : Array? - что это все такие такое и нужно ли оно?
6. Кажется разумным сохранять в TrainingsSlideData идентификатор тренировки из TrainingsData
7. Почему указаны типы данных Kotlin, а не SQLite ?

**Comment by zmm** [comment]
Необходимо:
- проверить работоспособность
- написать простой Instrumented-тест, проверяющий существование БД
